import { Camera, Building, DVR, DashboardStats } from '@/types/cctv'

export const MOCK_BUILDINGS: (Building & { cameras?: Camera[] })[] = [
  { id: 'bldg-1', code: 'GD-A', name: 'Gedung A (Kelas X & XI)', floors: 3, createdAt: new Date(), updatedAt: new Date() },
  { id: 'bldg-2', code: 'GD-B', name: 'Gedung B (Laboratorium)', floors: 3, createdAt: new Date(), updatedAt: new Date() },
  { id: 'bldg-3', code: 'GD-C', name: 'Gedung C (Administrasi & Guru)', floors: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 'bldg-4', code: 'GD-D', name: 'Gedung D (Fasilitas & Lapangan)', floors: 1, createdAt: new Date(), updatedAt: new Date() },
]

export const MOCK_DVRS: DVR[] = [
  { id: 'dvr-1', name: 'DVR Gedung A - Hikvision 16CH', brand: 'Hikvision', ipOrDomain: '192.168.1.101', rtspPort: 554, httpPort: 80, channels: 16, username: 'admin', password: '***', createdAt: new Date(), updatedAt: new Date() },
  { id: 'dvr-2', name: 'DVR Gedung B - Dahua 16CH', brand: 'Dahua', ipOrDomain: '192.168.1.102', rtspPort: 554, httpPort: 80, channels: 16, username: 'admin', password: '***', createdAt: new Date(), updatedAt: new Date() },
  { id: 'dvr-3', name: 'DVR Gedung C & D - HiLook 16CH', brand: 'HiLook', ipOrDomain: '192.168.1.103', rtspPort: 554, httpPort: 80, channels: 16, username: 'admin', password: '***', createdAt: new Date(), updatedAt: new Date() },
]

export const MOCK_CAMERAS: (Camera & { building?: Building; dvr?: Partial<DVR> })[] = [
  {
    id: 'cam-01',
    name: 'Ruang Kelas X-IPA 1',
    buildingId: 'bldg-1',
    dvrId: 'dvr-1',
    floor: 1,
    channel: 1,
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.101:554/Streaming/Channels/101',
    status: 'ONLINE',
    isFavorite: true,
    building: MOCK_BUILDINGS[0],
    dvr: MOCK_DVRS[0],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-02',
    name: 'Ruang Kelas X-IPA 2',
    buildingId: 'bldg-1',
    dvrId: 'dvr-1',
    floor: 1,
    channel: 2,
    streamUrl: 'https://playertest.longtailvideo.com/adaptive/bipbop/gear4/prog_index.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.101:554/Streaming/Channels/201',
    status: 'ONLINE',
    isFavorite: false,
    building: MOCK_BUILDINGS[0],
    dvr: MOCK_DVRS[0],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-03',
    name: 'Koridor Lantai 2 Gedung A',
    buildingId: 'bldg-1',
    dvrId: 'dvr-1',
    floor: 2,
    channel: 3,
    streamUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.101:554/Streaming/Channels/301',
    status: 'ONLINE',
    isFavorite: false,
    building: MOCK_BUILDINGS[0],
    dvr: MOCK_DVRS[0],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-04',
    name: 'Laboratorium Komputer 1',
    buildingId: 'bldg-2',
    dvrId: 'dvr-2',
    floor: 1,
    channel: 1,
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.102:554/cam/realmonitor?channel=1&subtype=0',
    status: 'ONLINE',
    isFavorite: true,
    building: MOCK_BUILDINGS[1],
    dvr: MOCK_DVRS[1],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-05',
    name: 'Laboratorium IPA & Kimia',
    buildingId: 'bldg-2',
    dvrId: 'dvr-2',
    floor: 2,
    channel: 2,
    streamUrl: 'https://playertest.longtailvideo.com/adaptive/bipbop/gear4/prog_index.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.102:554/cam/realmonitor?channel=2&subtype=0',
    status: 'ONLINE',
    isFavorite: false,
    building: MOCK_BUILDINGS[1],
    dvr: MOCK_DVRS[1],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-06',
    name: 'Perpustakaan Digital',
    buildingId: 'bldg-2',
    dvrId: 'dvr-2',
    floor: 3,
    channel: 3,
    streamUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.102:554/cam/realmonitor?channel=3&subtype=0',
    status: 'OFFLINE',
    isFavorite: false,
    building: MOCK_BUILDINGS[1],
    dvr: MOCK_DVRS[1],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-07',
    name: 'Lobi Utama & Resepsionis',
    buildingId: 'bldg-3',
    dvrId: 'dvr-3',
    floor: 1,
    channel: 1,
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.103:554/Streaming/Channels/101',
    status: 'ONLINE',
    isFavorite: true,
    building: MOCK_BUILDINGS[2],
    dvr: MOCK_DVRS[2],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-08',
    name: 'Ruang Guru & Tata Usaha',
    buildingId: 'bldg-3',
    dvrId: 'dvr-3',
    floor: 2,
    channel: 2,
    streamUrl: 'https://playertest.longtailvideo.com/adaptive/bipbop/gear4/prog_index.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.103:554/Streaming/Channels/201',
    status: 'ONLINE',
    isFavorite: false,
    building: MOCK_BUILDINGS[2],
    dvr: MOCK_DVRS[2],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-09',
    name: 'Ruang Kepala Sekolah',
    buildingId: 'bldg-3',
    dvrId: 'dvr-3',
    floor: 2,
    channel: 3,
    streamUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.103:554/Streaming/Channels/301',
    status: 'MAINTENANCE',
    isFavorite: false,
    building: MOCK_BUILDINGS[2],
    dvr: MOCK_DVRS[2],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-10',
    name: 'Lapangan Upacara & Olahraga',
    buildingId: 'bldg-4',
    dvrId: 'dvr-3',
    floor: 1,
    channel: 4,
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.103:554/Streaming/Channels/401',
    status: 'ONLINE',
    isFavorite: true,
    building: MOCK_BUILDINGS[3],
    dvr: MOCK_DVRS[3],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-11',
    name: 'Gerbang Masuk Utama',
    buildingId: 'bldg-4',
    dvrId: 'dvr-3',
    floor: 1,
    channel: 5,
    streamUrl: 'https://playertest.longtailvideo.com/adaptive/bipbop/gear4/prog_index.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.103:554/Streaming/Channels/501',
    status: 'ONLINE',
    isFavorite: true,
    building: MOCK_BUILDINGS[3],
    dvr: MOCK_DVRS[3],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cam-12',
    name: 'Area Parkir Kendaraan',
    buildingId: 'bldg-4',
    dvrId: 'dvr-3',
    floor: 1,
    channel: 6,
    streamUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    rtspUrl: 'rtsp://admin:pass@192.168.1.103:554/Streaming/Channels/601',
    status: 'ONLINE',
    isFavorite: false,
    building: MOCK_BUILDINGS[3],
    dvr: MOCK_DVRS[3],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const MOCK_STATS: DashboardStats = {
  total: 12,
  online: 10,
  offline: 1,
  maintenance: 1,
  favorites: 5,
}
